fun main(args : Array<String>) {
//    var obj = kotlin_1_Variables()
//    obj.Variable()
//    var obj=Kotlin_2_DataType()
//    obj.dataType()
//    var obj = kotlin_3_TypeConversion()
//    obj.typeConversion()
//    var obj = Kotlin_4_Operator()
//    obj.arithmeticalOperator()
//    obj.relationalOperator()
//    obj.assignmentOperator()
//obj.unaryOperator()
//    var obj=Kotlin_5_TakingInputFronUsert()
//        obj.buyGroceries()
//    var obj=Kotlin_6_IfExpression()
//   println( obj.isAdult())
//    println(obj.whichDeveloper())
//    obj.buyJioSim()
//    var obj=Kotlin_7_WhenExpression()
//    obj.findDay()
//    var obj=Kotlin_8_ForLoop()
//    obj.forloopEx()
//    var obj=Kotlin_9_Do_DoWhilelLoop()
//    obj.whileLoop()
//    var obj=Kotlin_10_breakStatement()
//    obj.breakStatement()
//    var obj=Kotlin_11_continuestatement()
//    obj.continueStatement()
//    var obj=Kotlin_12_Function()
//    println(obj.add(2,76))
//    obj.printSomthing("you are great bro")
//    var obj=Kotlin_13_DefaultAndNamedArgument()
//    obj.namedArgument()
//    var obj=Kotlin_14_AnonymousOrLamdaFunction()
//   println( obj.addition(6,8))
//fun add(a :Int, b :Int) :Int{
//    return a+b
//}
//    fun showing(str :String){
//        println(str)
//    }
//    var obj =Kotlin_15_HigherOrderFunction()
//    obj.addition(6,9,::add)
//    obj.show("faster corp is an tech giant",::showing)
//val obj=Kotlin_17_String()
//    obj.stringProperties()
//    obj.stringFunctions()
//    val obj=kotlin_18_ExceptionHandling()
//    obj.handleException()
//var obj =Kotlin_20_ClassAndObject()
//    println("roll no. of student ${obj.rollNo()}")
//    println("collage name of student ${obj.collage()}")
//var obj = Kotlin_21_NestedAndInnerClass()
//    //calling nested class function
//    val nested=Kotlin_21_NestedAndInnerClass.Faster()
//    println(Kotlin_21_NestedAndInnerClass.Faster().FasterDigitalServices())
//    println(Kotlin_21_NestedAndInnerClass.Faster().FasterFinacialServices())
//    println(nested.FasterFinacialServices())
//    Kotlin_21_NestedAndInnerClass().FasterCompanies().FasterSaasProducts()
//    println(Kotlin_21_NestedAndInnerClass().FasterCompanies().showCompany())
//    var obj= Kotlin_22_Constructor("tata digital","BigBasket","E-commerce")
////    obj.show()
//    var obj=TataDigital()
//    obj.show()
//    var obj=Kotlin_24_AbstractClass("Tata","Tata Digital ")
//    obj.companyName(obj.comp)
//    obj.subsidiaryName(obj.subsidiary)
//obj.showSomthing()
//    var obj =TataMotors()
//    obj.autoCompany()
//    obj.vehicleType()
//    obj.speedUp()
//    obj.braking()
//    obj.show()
//    val obj = Kotlin_26_DataClass.Compan("Tata","Tata digital", "Software and Internet")
//    println(obj.component1())
//    println(obj.component2())
//    println(obj.component3())
//    println(obj)
//    var obj=Kotlin_28_ExtensionFunctionAndCompanionObject()
//    obj.show()
//    obj.write()
//    Kotlin_28_ExtensionFunctionAndCompanionObject.printSomthing("faster Corp is tech gaint ")
//    Kotlin_28_ExtensionFunctionAndCompanionObject.showComp()
//    var obj=Kotlin_27_SealedClass.SubClass1("faster corp")
//    println(obj.var1)
//    var obj2=Kotlin_27_SealedClass.Subclass4()
//    var obj=Kotlin_29_Generics<Int,String,String>(25)
//    obj.show("sorabh kumar")
//    obj.showCompany("Faster Corp")
//    var obj=Kotlin_30_Ranges()
//    obj.show()
//var obj=Kotlin_32_SetterAndGetter("soranhk")
//    println(obj.name)
//obj.name="kallu"
//    println()
//    println(obj.companyName)
//    println()
//    obj.companyName="Faster digital services"
//    println()
//    println(obj.companyName)
    var obj=Kotlin_31_Collections()
//    obj.showImuMap()
//    obj.showImuSet()
//    obj.arrList()
    obj.printHashMap()
    obj.printSet()
}

