fun main(args : Array<String>) {
//    var obj = kotlin_1_Variables()
//    obj.Variable()
//    var obj=Kotlin_2_DataType()
//    obj.dataType()
//    var obj = kotlin_3_TypeConversion()
//    obj.typeConversion()
//    var obj = Kotlin_4_Operator()
//    obj.arithmeticalOperator()
//    obj.relationalOperator()
//    obj.assignmentOperator()
//obj.unaryOperator()
//    var obj=Kotlin_5_TakingInputFronUsert()
//        obj.buyGroceries()
//    var obj=Kotlin_6_IfExpression()
//   println( obj.isAdult())
//    println(obj.whichDeveloper())
//    obj.buyJioSim()
//    var obj=Kotlin_7_WhenExpression()
//    obj.findDay()
//    var obj=Kotlin_8_ForLoop()
//    obj.forloopEx()
//    var obj=Kotlin_9_Do_DoWhilelLoop()
//    obj.whileLoop()
//    var obj=Kotlin_10_breakStatement()
//    obj.breakStatement()
//    var obj=Kotlin_11_continuestatement()
//    obj.continueStatement()
//    var obj=Kotlin_12_Function()
//    println(obj.add(2,76))
//    obj.printSomthing("you are great bro")
//    var obj=Kotlin_13_DefaultAndNamedArgument()
//    obj.namedArgument()
//    var obj=Kotlin_14_AnonymousOrLamdaFunction()
//   println( obj.addition(6,8))
//fun add(a :Int, b :Int) :Int{
//    return a+b
//}
//    fun showing(str :String){
//        println(str)
//    }
//    var obj =Kotlin_15_HigherOrderFunction()
//    obj.addition(6,9,::add)
//    obj.show("faster corp is an tech giant",::showing)
//val obj=Kotlin_17_String()
//    obj.stringProperties()
//    obj.stringFunctions()
//    val obj=kotlin_18_ExceptionHandling()
//    obj.handleException()
//var obj =Kotlin_20_ClassAndObject()
//    println("roll no. of student ${obj.rollNo()}")
//    println("collage name of student ${obj.collage()}")
//var obj = Kotlin_21_NestedAndInnerClass()
//    //calling nested class function
//    val nested=Kotlin_21_NestedAndInnerClass.Faster()
//    println(Kotlin_21_NestedAndInnerClass.Faster().FasterDigitalServices())
//    println(Kotlin_21_NestedAndInnerClass.Faster().FasterFinacialServices())
//    println(nested.FasterFinacialServices())
//    Kotlin_21_NestedAndInnerClass().FasterCompanies().FasterSaasProducts()
//    println(Kotlin_21_NestedAndInnerClass().FasterCompanies().showCompany())
//    var obj= Kotlin_22_Constructor("tata digital","BigBasket","E-commerce")
////    obj.show()
//    var obj=TataDigital()
//    obj.show()
}

